let wasmModule: typeof import('../wasm/flowscope_wasm') | null = null;
let initPromise: Promise<typeof import('../wasm/flowscope_wasm')> | null = null;

export interface InitWasmOptions {
  wasmUrl?: string;
}

/**
 * Initialize the WASM module. Safe to call multiple times (idempotent).
 * Returns the initialized WASM module.
 */
export async function initWasm(
  _options: InitWasmOptions = {}
): Promise<typeof import('../wasm/flowscope_wasm')> {
  // Return cached module if already initialized
  if (wasmModule) {
    return wasmModule;
  }

  // Return existing promise if initialization is in progress
  if (initPromise) {
    return initPromise;
  }

  initPromise = (async () => {
    try {
      // Dynamic import of the wasm module
      // With vite-plugin-wasm, the module auto-initializes on import
      const wasm = await import('../wasm/flowscope_wasm');

      // Explicitly initialize the WASM module
      if (typeof wasm.default === 'function') {
        await wasm.default();
      }

      // Verify that the module is actually initialized by checking for required functions
      if (!wasm.analyze_sql_json || typeof wasm.analyze_sql_json !== 'function') {
        throw new Error('WASM module loaded but analyze_sql_json function is not available');
      }

      wasmModule = wasm;
      return wasmModule;
    } catch (error) {
      initPromise = null; // Allow retry on failure
      throw new Error(
        `Failed to initialize WASM module: ${error instanceof Error ? error.message : String(error)}`
      );
    }
  })();

  return initPromise;
}

/**
 * Check if WASM module is initialized
 */
export function isWasmInitialized(): boolean {
  return wasmModule !== null;
}

/**
 * Get the initialized WASM module. Throws if not initialized.
 */
export function getWasmModule(): typeof import('../wasm/flowscope_wasm') {
  if (!wasmModule) {
    throw new Error('WASM module not initialized. Call initWasm() first.');
  }
  return wasmModule;
}

/**
 * Cleanup the WASM module and release resources
 */
export async function cleanupWasm(): Promise<void> {
  if (wasmModule) {
    // Check if the module has a cleanup/free method and call it
    if (typeof (wasmModule as any).__wbindgen_free !== 'undefined') {
      try {
        // WASM modules generated by wasm-bindgen typically have cleanup methods
        // This is a best-effort cleanup
        (wasmModule as any).__wbindgen_free?.();
      } catch (error) {
        // Ignore cleanup errors as they're non-critical
      }
    }
  }
  wasmModule = null;
  initPromise = null;
}

/**
 * Reset the WASM module (mainly for testing)
 */
export function resetWasm(): void {
  wasmModule = null;
  initPromise = null;
}
